export const myprojects = [
  {
    projectTitle: "Template-3 landing page",
    Subtitle:"Responsive Template-3 landing page Using HTML CSS Bootstrap",
    category: ["all", "css"],
    imgPath: "./../../../images/template3.png",
    link: "https://mustafakh33.github.io/Template-3/",
    github: "https://github.com/mustafakh33/Template-3",
  },
  {
    projectTitle: "Digital-agency Landing Page",
    Subtitle:"Responsive Digital-agency Landing Page Using HTML CSS ",
    category: ["all", "css"],
    imgPath: "./../../../images/digital-agency.png",
    link: "https://mustafakh33.github.io/DigitalAgency-landing-page/",
    github: "https://github.com/mustafakh33/DigitalAgency-landing-page",
  },
  {
    projectTitle: "Admin Dashboard",
    Subtitle:"Responsive Admin Dashboard Using HTML CSS ",
    category: ["all", "css"],
    imgPath: "./../../../images/admin-dashboard.png",
    link: "https://mustafakh33.github.io/Admin-DashBoard/",
    github: "https://github.com/mustafakh33/Admin-DashBoard",
  },
  {
    projectTitle: "Gaming Landing Page",
    Subtitle:"Responsive Gaming Landing Page Using HTML CSS Bootstrap And JavaScript",
    category: ["all", "css", "bootstrap"],
    imgPath: "./../../../images/gaming.png",
    link: "https://mustafakh33.github.io/Gaming-landing-page/",
    github: "https://github.com/mustafakh33/Gaming-landing-page",
  },
  {
    projectTitle: "Darky Landing Page",
    Subtitle:"Responsive Darky Landing Page Using HTML CSS Bootstrap",
    category: ["all", "css", "bootstrap"],
    imgPath: "./../../../images/darky.png",
    link: "https://mustafakh33.github.io/Darky-landing-page/",
    github: "https://github.com/mustafakh33/Darky-landing-page",
  },
  {
    projectTitle: "E-commerce website",
    Subtitle:"Responsive E-Commerce Website Using HTML CSS Bootstrap And JavaScript",
    category: ["all", "javascript", "bootstrap"],
    imgPath: "./../../../images/outstock.png",
    link: "https://ecommerce-website-913f6.firebaseapp.com/index.html",
    github: "https://github.com/mustafakh33/Ecommerce-website",
  },
  {
    projectTitle: "Restaurant Landing Page",
    Subtitle:"Responsive Restaurant Landing Page Using HTML CSS Bootstrap And JavaScript",
    category: ["all", "javascript", "bootstrap"],
    imgPath: "./../../../images/restorant.png",
    link: "https://mustafakh33.github.io/Restoran-landing-page/",
    github: "https://github.com/mustafakh33/Restoran-landing-page",
  },
  {
    projectTitle: "Harly Landing Page",
    Subtitle:"Responsive Harly Landing Page Using HTML CSS Bootstrap And JavaScript",
    category: ["all", "javascript", "bootstrap"],
    imgPath: "./../../../images/harly.png",
    link: "https://mustafakh33.github.io/Harley-landing-page/",
    github: "https://github.com/mustafakh33/Harley-landing-page",
  },
  {
     projectTitle: "crud project",
     Subtitle:"Responsive crud project Using HTML CSS  And JavaScript",
    category: ["all", "javascript"],
    imgPath: "./../../../images/crud.png",
    link: "https://mustafakh33.github.io/CRUDS-Projects/",
    github: "https://github.com/mustafakh33/CRUDS-Projects",
   },
  {
     projectTitle: "Islamic website",
     Subtitle:"Responsive Islamic Landing Page Using HTML CSS And JavaScript",
    category: ["all", "javascript"],
    imgPath: "./../../../images/islamic-website.png",
    link: "https://mustafakh33.github.io/Islamic-website/",
    github: "https://github.com/mustafakh33/Islamic-website",
   },
   {
    projectTitle: "signIn & signout ",
    Subtitle:"Responsive signIn & signout Website Using ReactJS And Firebase",
    category: ["all", "react"],
    imgPath: "./../../../images/signIn&signout.png",
    link: "https://signin-signout-78fc9.web.app/",
    github: "https://github.com/mustafakh33/signin_signout-React",
  },
  {
    projectTitle: "Todo List",
    Subtitle:"Responsive Todo List Project Using ReactJS",
    category: ["all", "react"],
    imgPath: "./../../../images/todoList-react.png",
    link: "https://todo-list-ad572.web.app/",
    github: "https://github.com/mustafakh33/Todo-list2-React",
  },
];
